### ISSUE TITLE
NullPointerException on DataReceivedCallback

### ISSUE THREAD

**Issue by rmenezes** [NordicSemiconductor/Android-BLE-Library#100]
I'm having the exception: NullPointerException on the DataReceivedCallback. I can read the information when it's notified by the first time, but it throws the exception at the second time. I was using the old version of the library without any issues, it looks like this problem only happens on this new version.

Here's my code:

```java
setNotificationCallback(mAmbientAllSensorsCharacteristic)
                .with(new DataReceivedCallback() {
                    @Override
                    public void onDataReceived(@androidx.annotation.NonNull BluetoothDevice device, @androidx.annotation.NonNull Data data) {
                        onAmbientUpdated(data.getValue());
                    }
                });

        enableNotifications(mAmbientAllSensorsCharacteristic).enqueue();
        writeCharacteristic(mAmbientAcquisitionCharacteristic, interval).enqueue();
```

And here's my exception:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bttcorp.btthealth, PID: 20131
    kotlin.KotlinNullPointerException
        at com.bttcorp.btteleven.ActivityMonitor.onValueUpdated(ActivityMonitor.kt:289)
        at com.bttcorp.btteleven.BTTDeviceManager.onValueUpdated(BTTDeviceManager.kt:103)
        at com.bttcorp.btteleven.services.Abreu1000V2Service.onAmbientUpdated(Abreu1000V2Service.java:334)
        at com.bttcorp.btteleven.services.Abreu1000V2Service.access$000(Abreu1000V2Service.java:41)
        at com.bttcorp.btteleven.services.Abreu1000V2Service$1.onDataReceived(Abreu1000V2Service.java:458)
        at no.nordicsemi.android.ble.ValueChangedCallback.notifyValueChanged(ValueChangedCallback.java:123)
        at no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.onCharacteristicChangedSafe(BleManager.java:2884)
        at no.nordicsemi.android.ble.MainThreadBluetoothGattCallback.lambda$onCharacteristicChanged$4(MainThreadBluetoothGattCallback.java:135)
        at no.nordicsemi.android.ble.-$$Lambda$MainThreadBluetoothGattCallback$7AU42XLOqZKSRIMVuifw3eecBbw.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
My device is a Google Pixel 2 running Android 9.

**Comment by philips77** [comment]
From the log I can see that the exception is thrown in your `ActivityMonitor.kt:289` class, not in the BLE library.
