### ISSUE TITLE
The program crashes when I call the disconnect().enqueue() method in onDataReceived callback(alpha10).

### ISSUE THREAD

**Issue by fuhaodev** [NordicSemiconductor/Android-BLE-Library#181]
Crash log:

```
2020-04-03 10:27:05.130 10294-10294/com.example.demo V/LiteBleClient: Disconnecting...
2020-04-03 10:27:05.130 10294-10294/com.example.demo D/LiteBleClient: gatt.disconnect()
2020-04-03 10:27:05.131 10294-10294/com.example.demo D/BluetoothGatt: cancelOpen() - device: A4:C1:38:88:91:D8
2020-04-03 10:27:05.132 10294-10329/com.example.demo D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=10 device=A4:C1:38:88:91:D8
2020-04-03 10:27:05.133 10294-10329/com.example.demo D/LiteBleClient: [Callback] Connection state changed with status: 0 and new state: 0 (DISCONNECTED)
2020-04-03 10:27:05.133 10294-10329/com.example.demo I/LiteBleClient: Disconnected
2020-04-03 10:27:05.134 10294-10329/com.example.demo D/LiteBleClient: gatt.close()
2020-04-03 10:27:05.134 10294-10329/com.example.demo D/BluetoothGatt: close()
2020-04-03 10:27:05.135 10294-10329/com.example.demo D/BluetoothGatt: unregisterApp() - mClientIf=10
2020-04-03 10:27:05.136 10294-10329/com.example.demo I/MiTalk: LiteBleClient:onManagerReady
2020-04-03 10:27:05.295 10294-10294/com.example.demo D/AndroidRuntime: Shutting down VM
2020-04-03 10:27:05.296 10294-10294/com.example.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.demo, PID: 10294
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.bluetooth.BluetoothDevice android.bluetooth.BluetoothGatt.getDevice()' on a null object reference
        at no.nordicsemi.android.ble.BleManagerHandler.lambda$internalDisconnect$5$BleManagerHandler(BleManagerHandler.java:590)
        at no.nordicsemi.android.ble.-$$Lambda$BleManagerHandler$uzvN3mTy1hAgrH2WPsJcnNqLJcE.run(Unknown Source:2)
        at no.nordicsemi.android.ble.BleManagerHandler.lambda$postConnectionStateChange$15(BleManagerHandler.java:1247)
        at no.nordicsemi.android.ble.-$$Lambda$BleManagerHandler$4r-nMh00pvleAsXLi5_Uq8GIr38.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

**Comment by philips77** [comment]
Hi,
Thanks. It's fixed now in the latest alpha12.
