### ISSUE TITLE
NullPointerException in internalConnect

### ISSUE THREAD

**Issue by chris-prop** [NordicSemiconductor/Android-BLE-Library#338]
We received the following stack trace in a crash report. We are using 2.3.1.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean no.nordicsemi.android.ble.TimeoutableRequest.z(android.bluetooth.BluetoothDevice)' on a null object reference
       at no.nordicsemi.android.ble.BleManagerHandler.internalConnect(BleManagerHandler.java:489)
       at no.nordicsemi.android.ble.BleManagerHandler.access$2700(BleManagerHandler.java:57)
       at no.nordicsemi.android.ble.BleManagerHandler$3.lambda$onConnectionStateChange$3(BleManagerHandler.java:1803)
       at no.nordicsemi.android.ble.BleManagerHandler$3.$r8$lambda$JA4A3XYfhUGlXRcFBJ3rJoQBsvs(BleManagerHandler.java)
       at no.nordicsemi.android.ble.BleManagerHandler$3$$InternalSyntheticLambda$0$8d19e6ce89fe9f2131286e70e9cf3a0cbc09693786214531c3c4ed467ff11a14$3.run(BleManagerHandler.java:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7615)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

Based on the line numbers, it looks like `this.connectRequest` is `null`.

**Comment by philips77** [comment]
Thank you for the bug report. I'll look into that.
