### ISSUE TITLE
Crash from refreshDeviceCache call

### ISSUE THREAD

**Issue by GITkrisbiketeam** [NordicSemiconductor/Android-BLE-Library#392]
I encountered a crash :
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothGatt.discoverServices()' on a null object reference
  at no.nordicsemi.android.ble.BleManagerHandler.lambda$nextRequest$27(BleManagerHandler.java:3312)
  at no.nordicsemi.android.ble.BleManagerHandler.$r8$lambda$hkBr83nOUPKozXBGq-VSZzTAeIw(BleManagerHandler.java:-1)
  at no.nordicsemi.android.ble.BleManagerHandler$$InternalSyntheticLambda$0$891dd13096bfc1de4c44040bc49f130653fc73add4ceb05b5fd5eb8d11d3e44c$4.run(BleManagerHandler.java:-1:-1)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6119)
  at java.lang.reflect.Method.invoke(Method.java:-2)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Android: 7.1.1 BLE-Library version is 2.3.1 stack trace comes from REFRESH_CACHE request handler which is not synchronized (just like other calls to bluetoothGatt.discoverServices())
```java
                     case REFRESH_CACHE: {
				final Request r = request;
				result = internalRefreshDeviceCache();
				if (result) {
					postDelayed(() -> {
						log(Log.INFO, "Cache refreshed");
						r.notifySuccess(bluetoothDevice);
						this.request = null;
						if (awaitingRequest != null) {
							awaitingRequest.notifyFail(bluetoothDevice, FailCallback.REASON_NULL_ATTRIBUTE);
							awaitingRequest = null;
						}
						taskQueue.clear();
						initQueue = null;
						if (connected) {
							// Invalidate all services and characteristics
							onServicesInvalidated();
							onDeviceDisconnected();
							// And discover services again
							serviceDiscoveryRequested = true;
							servicesDiscovered = false;
							log(Log.VERBOSE, "Discovering Services...");
							log(Log.DEBUG, "gatt.discoverServices()");
							bluetoothGatt.discoverServices();
						}
					}, 200);
				}
				break;
			}
```
shouldn't this if(conneced) block be synchronized like other calls to bluetoothGatt and connected
this is probably also related to https://github.com/NordicSemiconductor/Android-BLE-Library/issues/375

**Comment by philips77** [comment]
Yes, that seems to be the same as mentioned issue. I'll fix it now and release 2.5.1.
