### ISSUE TITLE
java.lang.IllegalAccessError: Illegal class access

### ISSUE THREAD

**Issue by williamtan37** [NordicSemiconductor/Android-BLE-Library#436]
Hello. Would appreciate any insight, been stuck for a day reading solutions to no avail.

Currently when I run my app locally, I have no isues.
But when I run it after being built on jenkins, I get:

    java.lang.IllegalAccessError: Illegal class access: 'com.code.nudge.neo.services.stk.BLEManager' attempting to access 'no.nordicsemi.android.ble.BleManagerHandler' (declaration of 'com.code.nudge.neo.services.stk.BLEManager' appears in base.apk!classes3.dex)
        at com.code.nudge.neo.services.stk.BLEManager.access$enableNotifications(Unknown Source:9)
        at com.code.nudge.neo.services.stk.BLEManager$BLEManagerGattCallback.u2(Unknown Source:36)
        at no.nordicsemi.android.ble.BleManagerHandler$3.onServicesDiscovered(Unknown Source:456)
        at android.bluetooth.BluetoothGatt$1$6.run(BluetoothGatt.java:412)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

Any ideas?

**Comment by philips77** [comment]
If it runs locally, but not when released, check Proguard configuration. You may also analyze the APK from Jenkins and check differences.
I haven't seen similar issue, sorry.
