### ISSUE TITLE
Payload (250 bytes) too long for MTU: 249

### ISSUE THREAD

**Issue by tonkarhu** [NordicSemiconductor/Android-BLE-Library#447]
Problem I started to see today:
```
E/Uploader: Upload failed
    Payload (250 bytes) too long for MTU: 249
        at io.runtime.mcumgr.ble.McuMgrBleTransport.lambda$send$0$io-runtime-mcumgr-ble-McuMgrBleTransport(McuMgrBleTransport.java:356)
        at io.runtime.mcumgr.ble.McuMgrBleTransport$$ExternalSyntheticLambda3.onRequestCompleted(Unknown Source:13)
        at no.nordicsemi.android.ble.Request.lambda$notifySuccess$1$no-nordicsemi-android-ble-Request(Request.java:1239)
        at no.nordicsemi.android.ble.Request$$ExternalSyntheticLambda2.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)

```
I solved this by downgrading     
`no.nordicsemi.android:mcumgr-ble:1.5.0 `
to 
`no.nordicsemi.android:mcumgr-ble:1.4.1'`

in my app and it works now. 

My guess is that the "Ble library update":
"BLE library updated to version 2.6.0-alpha04 by @philips77" in @https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/pull/84
has to do something with this issue.

**Comment by philips77** [comment]
The issue you're having is not related to BLE library. 
The root cause seems to be this PR: 
https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager/pull/83
