### ISSUE TITLE
Null reference exception when calling disconnect

### ISSUE THREAD

**Issue by david-gettins** [NordicSemiconductor/Android-BLE-Library#535]
I have recently updated to `v2.7.2` amongst [other oddities](https://github.com/NordicSemiconductor/Android-BLE-Library/issues/534) I have found disconnect throws a `NullPointerException` every time I call it.

_To Reproduce_

- Connect a peripheral
- Call `disconnect.enqueue()` or `.suspend()`
- See the exception is thrown

_Notes_

The peripheral is disconnected despite the `NullPointerException`. I verified this by scanning for it after disconnect and seeing the error.

**Comment by david-gettins** [comment]
Here is the stack trace up to the point were it hits my code:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGattServer.cancelConnection(android.bluetooth.BluetoothDevice)' on a null object reference
                                                                                                    	at no.nordicsemi.android.ble.BleServerManager.cancelConnection(BleServerManager.java:190)
                                                                                                    	at no.nordicsemi.android.ble.BleManagerHandler.internalDisconnect(BleManagerHandler.java:746)
                                                                                                    	at no.nordicsemi.android.ble.BleManagerHandler.nextRequest(BleManagerHandler.java:3495)
                                                                                                    	at no.nordicsemi.android.ble.BleManagerHandler.enqueue(BleManagerHandler.java:1550)
                                                                                                    	at no.nordicsemi.android.ble.Request.enqueue(Request.java:1209)
                                                                                                    	at no.nordicsemi.android.ble.TimeoutableRequest.enqueue(TimeoutableRequest.java:106)
                                                                                                    	at no.nordicsemi.android.ble.ktx.RequestSuspendKt.suspendCancellable(RequestSuspend.kt:406)
                                                                                                    	at no.nordicsemi.android.ble.ktx.RequestSuspendKt.suspend(RequestSuspend.kt:40)
```
